### ISSUE TITLE
Not working on arm64

### ISSUE THREAD

**Issue by Spaccesi** [pilotak/docker-rpi-fan#2]
It was working perfectly until I update the os to 64-bits

I got this error

```Traceback (most recent call last):
  File "./fan.py", line 30, in <module>
    import RPi.GPIO as GPIO
  File "/root/.local/lib/python3.8/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!

**Comment by pilotak** [comment]
ok, but there is nothing i can do with it, it uses this lib https://pypi.org/project/RPi.GPIO
